---
# tasks file for roles/frontend

- name: Install {{ package }}
  yum:
    name: "{{ package }}"
    state: latest

- name: Enable {{ package }} at boot
  service:
    name: "{{ package }}"
    state: started
    enabled: true

- name: Configure {{ package }} to load balance over app servers
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart_haproxy
