---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Fetch Instance Info
    os_server_facts:
     cloud: ospcloud
    register: result

  - name: Add host
    add_host:
     name: "{{ item.public_v4 }}"
     group: "{{ item.metadata.group }}"
     ansible_ssh_private_key_file: /root/.ssh/openstack.pem
     ansible_user: cloud-user
    with_items: "{{result.ansible_facts.openstack_servers}}"
  - name: Add host
    add_host:
     name: "{{ item.public_v4 }}"
     group: "{{ item.metadata.deployment_name }}"
     ansible_ssh_private_key_file: /root/.ssh/openstack.pem
     ansible_user: cloud-user
    with_items: "{{result.ansible_facts.openstack_servers}}"
- hosts: apps
  become: yes
  roles:
  - app-tier
- hosts: appdbs
  become: yes
  roles:
  - db-tier
- hosts: frontends
  become: yes
  roles:
  - frontend

